---
apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secret
  namespace: guacamole
type: Opaque
data:
  db_admin_user: cm9vdA==
  db_admin_password: UzNjcmV0TVlTUUxA
  db_user: Z3VhY2Ftb2xl
  db_password: Q2hlbm5haURCQUA= 
