apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-pv-claim
  namespace: guacamole
  labels:
    app: guacamole
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: guacamole-pv-volume
  namespace: guacamole
  labels:
    type: local
    app: guacamole
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/guacamole/sql"
  persistentVolumeReclaimPolicy: Retain
